apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    k8s-app: {{ .Values.appName }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    k8s-app: {{ .Values.appName }}